### ISSUE TITLE
invalid token !

### ISSUE THREAD

**Issue by electro60** [Javinator9889/telegram-yt_mp3-bot#1]
I put my bot token in "token.txt" but when i try to run TeleBotSongDownloader.py

=====================================

This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
This is free software, and you are welcome to redistribute itunder certain conditions; type `show c' for details.
Traceback (most recent call last):
  File "TeleBotSongDownloader.py", line 399, in <module>
    updater = Updater(token["Telegram"], workers=200)             # Starts 200 threads for "updater" (declared with '@run_async' decorator)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/updater.py", line 112, in __init__
    self.bot = Bot(token, base_url, request=self._request)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 87, in __init__
    self.token = self._validate_token(token)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 109, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token

**Comment by Javinator9889** [comment]
Now it's a dictionary, not just a token
